name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build (Vite -> dist)
        run: npm run build

      # ✅ Deploy só em push direto na main (PR não usa secret)
      - name: Deploy to Azure Static Web Apps
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.AZURE_STATIC_WEB_APPS_API_TOKEN != ''
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Alguns releases esperam 'deployment_token'; outros, 'azure_static_web_apps_api_token'.
          # Passamos os dois por segurança.
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "dist"
          production_branch: "main"
          skip_app_build: true

  # Mantém o close do ambiente de PR, sem secrets
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
