name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build (Vite -> dist)
        run: npm run build

      # OIDC: usa o 'core' global (NÃO usar require)
      - name: Get GitHub ID Token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const id = await core.getIDToken();
            core.setOutput('token', id);

      - name: Deploy to Azure Static Web Apps (OIDC)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "/"        # ajuste se seu app estiver em subpasta
          output_location: "dist"  # Vite -> dist
          production_branch: "main"
          skip_app_build: true
          github_id_token: ${{ steps.oidc.outputs.token }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
