name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # <- OIDC habilitado

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build (Vite -> dist)
        run: npm run build

      # 🚀 Deploy via OIDC (sem deployment token)
      - name: Deploy to Azure Static Web Apps (OIDC)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "."       # seu app está na raiz
          output_location: "dist" # Vite gera dist
          production_branch: "main"
          skip_app_build: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # ajuda a action a ler o repo/commit

  # Fecha ambiente de PR (preview) quando o PR é fechado
  close_pr_env:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
