name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build (Vite -> dist)
        run: npm run build

      # Deploy só em push direto na main e se o secret existir
      - name: Deploy to Azure Static Web Apps
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.AZURE_STATIC_WEB_APPS_API_TOKEN != '' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Use APENAS o deployment_token (algumas versões ignoram o outro nome)
          deployment_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "dist"
          production_branch: "main"
          skip_app_build: true

  close_pull_request_job:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
