name: Azure SWA – Static Files

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 🧪 (opcional) prova que o index existe na raiz
      - name: Sanity check
        run: |
          test -f index.html || (echo "index.html não encontrado na raiz" && exit 1)

      - name: Deploy (token)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "."   # publica a raiz (index.html, styles.css, main.js)
          output_location: "" # sem build
          production_branch: "main"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
